<a href="https://colab.research.google.com/github/sathishkaran31/AIML-PREREQ-LEARNER/blob/main/matrix_topics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First, let's import the `numpy` library, which is essential for numerical operations in Python, especially with arrays and matrices.

In [ ]:
import numpy as np

# Create the first matrix (3x3)
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create the second matrix (3x3)
matrix_b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:")
display(matrix_a)

print("Matrix B:")
display(matrix_b)

Matrix A:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Matrix B:


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Now, let's perform some basic mathematical operations on these matrices.

In [ ]:
# Matrix Addition
matrix_sum = matrix_a + matrix_b
print("Matrix A + Matrix B:")
display(matrix_sum)

# Matrix Subtraction
matrix_difference = matrix_a - matrix_b
print("Matrix A - Matrix B:")
display(matrix_difference)

# Element-wise Multiplication (Hadamard product)
matrix_element_wise_product = matrix_a * matrix_b
print("Matrix A * Matrix B (element-wise):")
display(matrix_element_wise_product)

# Matrix Multiplication (Dot product)
# Note: For standard matrix multiplication, use np.dot() or @ operator
matrix_dot_product = np.dot(matrix_a, matrix_b)
print("Matrix A @ Matrix B (dot product):")
display(matrix_dot_product)

Matrix A + Matrix B:


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

Matrix A - Matrix B:


array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

Matrix A * Matrix B (element-wise):


array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

Matrix A @ Matrix B (dot product):


array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

First, let's ensure we have `numpy` imported, as it's essential for matrix operations.

In [ ]:
import numpy as np

### Scalar Matrix

A scalar matrix is a diagonal matrix where all the diagonal elements are equal. It can be thought of as a scalar multiple of an identity matrix. Here, we'll create a 3x3 scalar matrix.

In [ ]:
# Define a scalar value
scalar_value = 5

# Create a 3x3 identity matrix
identity_matrix = np.identity(3)

# Create a scalar matrix by multiplying the identity matrix by the scalar value
scalar_matrix = scalar_value * identity_matrix

print("Identity Matrix:")
display(identity_matrix)

print(f"\nScalar Matrix (Identity Matrix * {scalar_value}):")
display(scalar_matrix)

Identity Matrix:


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


Scalar Matrix (Identity Matrix * 5):


array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

### Vector Matrix

In `numpy`, a vector can be represented as a 1D array. When we talk about a 'vector matrix', it usually refers to representing a vector as a row or column matrix. Let's create a 1D vector and then show its representation as a row and column matrix.

In [ ]:
# Create a 1D vector
vector_1d = np.array([10, 20, 30, 40])

print("Original 1D Vector:")
display(vector_1d)

# Reshape to a row vector (1 row, N columns)
row_vector = vector_1d.reshape(1, -1)
print("\nRow Vector (1x4 matrix representation):")
display(row_vector)

# Reshape to a column vector (N rows, 1 column)
column_vector = vector_1d.reshape(-1, 1)
print("\nColumn Vector (4x1 matrix representation):")
display(column_vector)

Original 1D Vector:


array([10, 20, 30, 40])


Row Vector (1x4 matrix representation):


array([[10, 20, 30, 40]])


Column Vector (4x1 matrix representation):


array([[10],
       [20],
       [30],
       [40]])

### Transpose of a Matrix

Transposition is an operation that flips a matrix over its diagonal, switching the row and column indices of the matrix. In `numpy`, you can easily get the transpose using the `.T` attribute or `np.transpose()` function.

In [ ]:
# Let's use our original matrix_a from the previous example
# If matrix_a is not defined, run the previous cells or define it here:
# matrix_a = np.array([
#     [1, 2, 3],
#     [4, 5, 6],
#     [7, 8, 9]
# ])

# Create a sample matrix
sample_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original Matrix:")
display(sample_matrix)

# Get the transpose using .T attribute
transpose_matrix_t = sample_matrix.T
print("\nTranspose using .T:")
display(transpose_matrix_t)

# Get the transpose using np.transpose() function
transpose_matrix_func = np.transpose(sample_matrix)
print("\nTranspose using np.transpose():")
display(transpose_matrix_func)

Original Matrix:


array([[1, 2, 3],
       [4, 5, 6]])


Transpose using .T:


array([[1, 4],
       [2, 5],
       [3, 6]])


Transpose using np.transpose():


array([[1, 4],
       [2, 5],
       [3, 6]])